### ISSUE TITLE
Erro r when starting channel

### ISSUE THREAD

**Issue by rikardfries** [emilsvennesson/kodi-cmore#27]
When I try to start a channel in Cmore I get this:
Any thoughts or ideas to what is happening.?
It has worked for a long time but now... I get this.

20:14:04.094 T:10956   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPSConnectionPool(host='restapi.cmore.se', port=443): Max retries exceeded with url: /api/tve_web/asset/3351495/play.json?protocol=VUDASH (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1A8FA950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
                                            Traceback (most recent call last):
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\plugin.video.cmore\default.py", line 5, in <module>
                                                addon.run()
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\plugin.video.cmore\addon.py", line 14, in run
                                                router(sys.argv[2][1:])  # trim the leading '?' from the plugin call paramstring
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\plugin.video.cmore\addon.py", line 386, in router
                                                helper.play_item(params['video_id'])
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\plugin.video.cmore\resources\lib\kodihelper.py", line 216, in play_item
                                                stream = self.c.get_stream(video_id)
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\plugin.video.cmore\resources\lib\cmore.py", line 255, in get_stream
                                                data_dict = self.make_request(url, 'get', params=params, headers=headers)['playback']
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\plugin.video.cmore\resources\lib\cmore.py", line 66, in make_request
                                                req = self.http_session.get(url, params=params, headers=headers)
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 521, in get
                                                return self.request('GET', url, **kwargs)
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 508, in request
                                                resp = self.send(prep, **send_kwargs)
                                             File "C:\Users\rikar\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 618, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\rikar\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 508, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPSConnectionPool(host='restapi.cmore.se', port=443): Max retries exceeded with url: /api/tve_web/asset/3351495/play.json?protocol=VUDASH (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1A8FA950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
                                            -->End of Python script error report<--

**Comment by emilsvennesson** [comment]
Hi! It looks like you're not on the latest git version. They probably shut down their old playback API.

https://github.com/emilsvennesson/kodi-cmore/commit/733c232800f902057044b0a137795f8b22d1e47f made the switch to the new one.

**Comment by rikardfries** [comment]
Sorry my bad. You are absolutely right. Fixed. Thank you,
