### ISSUE TITLE
Can't resolve account.cmore.se

### ISSUE THREAD

**Issue by ernstp** [emilsvennesson/kodi-cmore#40]
I can't resolve the hostname from my desktop either.

2020-08-17 17:52:49.550 T:2354295664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPSConnectionPool(host='account.cmore.se', port=443): Max retries exceeded with url: /session?client=cmore-android&legacy=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x99518a70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.cmore/default.py", line 5, in <module>
                                                addon.run()
                                              File "/storage/.kodi/addons/plugin.video.cmore/addon.py", line 14, in run
                                                router(sys.argv[2][1:])  # trim the leading '?' from the plugin call paramstring
                                              File "/storage/.kodi/addons/plugin.video.cmore/addon.py", line 398, in router
                                                if helper.check_for_prerequisites():
                                              File "/storage/.kodi/addons/plugin.video.cmore/resources/lib/kodihelper.py", line 88, in check_for_prerequisites
                                                if self.set_locale(self.get_setting('locale')) and self.set_login_credentials() and self.check_for_credentials():
                                              File "/storage/.kodi/addons/plugin.video.cmore/resources/lib/kodihelper.py", line 118, in check_for_credentials
                                                self.login_process()
                                              File "/storage/.kodi/addons/plugin.video.cmore/resources/lib/kodihelper.py", line 125, in login_process
                                                self.c.login(username, password, operator)
                                              File "/storage/.kodi/addons/plugin.video.cmore/resources/lib/cmore.py", line 182, in login
                                                credentials = self.make_request(url, method, params=params, payload=payload)
                                              File "/storage/.kodi/addons/plugin.video.cmore/resources/lib/cmore.py", line 70, in make_request
                                                req = self.http_session.post(url, params=params, data=payload, headers=headers)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 581, in post
                                                return self.request('POST', url, data=data, json=json, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPSConnectionPool(host='account.cmore.se', port=443): Max retries exceeded with url: /session?client=cmore-android&legacy=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x99518a70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
                                            -->End of Python script error report<--
2020-08-17 17:52:49.657 T:2300552048   ERROR: GetDirectory - Error getting plugin://plugin.video.cmore/
2020-08-17 17:52:49.663 T:3011272720   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cmore/) failed

**Comment by mrpg99** [comment]
i also have the same issue

**Comment by emilsvennesson** [comment]
I do believe this has been fixed in the latest version on git. The Kodi repository version is not up to date and I can't push out a new version until python3 support has been sorted.

Try installing https://github.com/emilsvennesson/kodi-cmore/archive/master.zip.

**Comment by apaatelm** [comment]
Instal link didn't work, should it be still valid?
