### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by mrpg99** [emilsvennesson/kodi-cmore#41]
Hi,
Downloaded the latest version here from github, but the plugin no longer starts : 

I get these messages in the log : 

2021-05-03 13:31:58.857 T:140319188732608   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.cmore/)
2021-05-03 13:31:58.857 T:140319188732608   DEBUG:   ParentPath = [addons://sources/video]
2021-05-03 13:31:58.858 T:140315960809216   DEBUG: Thread waiting start, auto delete: false
2021-05-03 13:31:58.867 T:140315952416512   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.cmore] took 10 ms
2021-05-03 13:31:58.867 T:140315960809216   DEBUG: StartScript - calling plugin C More('plugin://plugin.video.cmore/','80','','resume:false')
2021-05-03 13:31:58.868 T:140316007565056   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-05-03 13:31:58.868 T:140316007565056    INFO: initializing python engine.
2021-05-03 13:31:58.868 T:140316007565056   DEBUG: CPythonInvoker(155, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): start processing
2021-05-03 13:31:58.911 T:140316007565056   DEBUG: -->Python Interpreter Initialized<--
2021-05-03 13:31:58.911 T:140316007565056   DEBUG: CPythonInvoker(155, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): the source file to load is "/home/mrpg/.kodi/addons/plugin.video.cmore/default.py"
2021-05-03 13:31:58.911 T:140316007565056   DEBUG: CPythonInvoker(155, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): setting the Python path to /home/mrpg/.kodi/addons/plugin.video.cmore:/home/mrpg/.kodi/addons/script.module.certifi/lib:/home/mrpg/.kodi/addons/script.module.chardet/lib:/home/mrpg/.kodi/addons/script.module.idna/lib:/home/mrpg/.kodi/addons/script.module.inputstreamhelper/lib:/home/mrpg/.kodi/addons/script.module.requests/lib:/home/mrpg/.kodi/addons/script.module.urllib3/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages
2021-05-03 13:31:58.911 T:140316007565056   DEBUG: CPythonInvoker(155, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): entering source directory /home/mrpg/.kodi/addons/plugin.video.cmore
2021-05-03 13:31:58.911 T:140316007565056   DEBUG: CPythonInvoker(155, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): instantiating addon using automatically obtained id of "plugin.video.cmore" dependent on version 2.25.0 of the xbmc.python api
2021-05-03 13:31:58.958 T:140319188732608   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-05-03 13:31:59.136 T:140316007565056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named iso8601
                                            Traceback (most recent call last):
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/default.py", line 2, in <module>
                                                from resources.lib import addon
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/resources/lib/addon.py", line 5, in <module>
                                                from resources.lib.kodihelper import KodiHelper
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/resources/lib/kodihelper.py", line 5, in <module>
                                                from cmore import CMore
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/resources/lib/cmore.py", line 14, in <module>
                                                import iso8601
                                            ImportError: No module named iso8601
                                            -->End of Python script error report<--
2021-05-03 13:31:59.136 T:140316007565056   DEBUG: onExecutionDone(155, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py)
2021-05-03 13:31:59.136 T:140319188732608   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-05-03 13:31:59.139 T:140316007565056    INFO: Python interpreter stopped
2021-05-03 13:31:59.139 T:140316007565056   DEBUG: Thread LanguageInvoker 140316007565056 terminating
2021-05-03 13:31:59.149 T:140315960809216   ERROR: GetDirectory - Error getting plugin://plugin.video.cmore/
2021-05-03 13:31:59.149 T:140315960809216   DEBUG: Thread waiting 140315960809216 terminating
2021-05-03 13:31:59.152 T:140319188732608   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-05-03 13:31:59.152 T:140319188732608   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cmore/) failed
2021-05-03 13:31:59.152 T:140319188732608   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)
2021-05-03 13:31:59.152 T:140319188732608   DEBUG:   ParentPath = [addons://sources/]
2021-05-03 13:31:59.152 T:140315960809216   DEBUG: Thread waiting start, auto delete: false
2021-05-03 13:31:59.156 T:140315960809216   DEBUG: Thread waiting 140315960809216 terminating
2021-05-03 13:31:59.157 T:140315960809216   DEBUG: Thread BackgroundLoader start, auto delete: false
2021-05-03 13:31:59.159 T:140315960809216 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-poster.jpg
2021-05-03 13:31:59.159 T:140315960809216 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-poster.png
2021-05-03 13:31:59.159 T:140315960809216 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-banner.jpg
2021-05-03 13:31:59.159 T:140315960809216 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-banner.png
2021-05-03 13:31:59.159 T:140315960809216   DEBUG: Thread BackgroundLoader 140315960809216 terminating
2021-05-03 13:32:00.267 T:140315969201920   DEBUG: CWebServer[8080]: request received for /jsonrpc
2021-05-03 13:32:05.627 T:140319188732608   DEBUG: Previous line repeats 23 times.
2021-05-03 13:32:05.627 T:140319188732608   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2021-05-03 13:32:06.174 T:140319188732608    INFO: CheckIdle - Closing session to http://www.msftncsi.com (easy=0x7f9e48c842a0, multi=(nil))
2021-05-03 13:32:06.272 T:140315830015744   DEBUG: CWebServer[8080]: request received for /jsonrpc
2021-05-03 13:32:18.335 T:140316354987776   DEBUG: Previous line repeats 45 times.
2021-05-03 13:32:18.335 T:140316354987776   DEBUG: EventClient: button code 0 pressed
2021-05-03 13:32:18.347 T:140319188732608   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2021-05-03 13:32:18.347 T:140319188732608   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.cmore/)
2021-05-03 13:32:18.347 T:140319188732608   DEBUG:   ParentPath = [addons://sources/video]
2021-05-03 13:32:18.348 T:140315969201920   DEBUG: Thread waiting start, auto delete: false
2021-05-03 13:32:18.356 T:140315902068480   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.cmore] took 9 ms
2021-05-03 13:32:18.357 T:140315969201920   DEBUG: StartScript - calling plugin C More('plugin://plugin.video.cmore/','81','','resume:false')
2021-05-03 13:32:18.357 T:140315830015744   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-05-03 13:32:18.357 T:140315830015744    INFO: initializing python engine.
2021-05-03 13:32:18.357 T:140315830015744   DEBUG: CPythonInvoker(156, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): start processing
2021-05-03 13:32:18.409 T:140315830015744   DEBUG: -->Python Interpreter Initialized<--
2021-05-03 13:32:18.409 T:140315830015744   DEBUG: CPythonInvoker(156, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): the source file to load is "/home/mrpg/.kodi/addons/plugin.video.cmore/default.py"
2021-05-03 13:32:18.410 T:140315830015744   DEBUG: CPythonInvoker(156, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): setting the Python path to /home/mrpg/.kodi/addons/plugin.video.cmore:/home/mrpg/.kodi/addons/script.module.certifi/lib:/home/mrpg/.kodi/addons/script.module.chardet/lib:/home/mrpg/.kodi/addons/script.module.idna/lib:/home/mrpg/.kodi/addons/script.module.inputstreamhelper/lib:/home/mrpg/.kodi/addons/script.module.requests/lib:/home/mrpg/.kodi/addons/script.module.urllib3/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages
2021-05-03 13:32:18.410 T:140315830015744   DEBUG: CPythonInvoker(156, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): entering source directory /home/mrpg/.kodi/addons/plugin.video.cmore
2021-05-03 13:32:18.411 T:140315830015744   DEBUG: CPythonInvoker(156, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py): instantiating addon using automatically obtained id of "plugin.video.cmore" dependent on version 2.25.0 of the xbmc.python api
2021-05-03 13:32:18.448 T:140319188732608   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-05-03 13:32:18.607 T:140315830015744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named iso8601
                                            Traceback (most recent call last):
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/default.py", line 2, in <module>
                                                from resources.lib import addon
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/resources/lib/addon.py", line 5, in <module>
                                                from resources.lib.kodihelper import KodiHelper
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/resources/lib/kodihelper.py", line 5, in <module>
                                                from cmore import CMore
                                              File "/home/mrpg/.kodi/addons/plugin.video.cmore/resources/lib/cmore.py", line 14, in <module>
                                                import iso8601
                                            ImportError: No module named iso8601
                                            -->End of Python script error report<--
2021-05-03 13:32:18.607 T:140315830015744   DEBUG: onExecutionDone(156, /home/mrpg/.kodi/addons/plugin.video.cmore/default.py)
2021-05-03 13:32:18.608 T:140319188732608   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-05-03 13:32:18.610 T:140315830015744    INFO: Python interpreter stopped
2021-05-03 13:32:18.610 T:140315830015744   DEBUG: Thread LanguageInvoker 140315830015744 terminating
2021-05-03 13:32:18.618 T:140315969201920   ERROR: GetDirectory - Error getting plugin://plugin.video.cmore/
2021-05-03 13:32:18.618 T:140315969201920   DEBUG: Thread waiting 140315969201920 terminating
2021-05-03 13:32:18.623 T:140319188732608   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-05-03 13:32:18.624 T:140319188732608   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cmore/) failed
2021-05-03 13:32:18.624 T:140319188732608   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)
2021-05-03 13:32:18.624 T:140319188732608   DEBUG:   ParentPath = [addons://sources/]
2021-05-03 13:32:18.624 T:140315969201920   DEBUG: Thread waiting start, auto delete: false
2021-05-03 13:32:18.627 T:140315969201920   DEBUG: Thread waiting 140315969201920 terminating
2021-05-03 13:32:18.628 T:140315969201920   DEBUG: Thread BackgroundLoader start, auto delete: false
2021-05-03 13:32:18.630 T:140315969201920 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-poster.jpg
2021-05-03 13:32:18.630 T:140315969201920 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-poster.png
2021-05-03 13:32:18.630 T:140315969201920 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-banner.jpg
2021-05-03 13:32:18.630 T:140315969201920 WARNING: CreateLoader - unsupported protocol(script) in script://screensaver.atv4/-banner.png

**Comment by mrpg99** [comment]
no longer an active project?
